name: Deploy App

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches-ignore:
      - '**'
jobs:
  install-and-test:
    runs-on: macOS-latest
  steps: 
      - uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: |
          yarn install
      - name: Run tests
        run: |
          yarn test
      - name: Check Format
        run: yarn lint